### ISSUE TITLE
problems with getting a 'fixefp reading'

### ISSUE THREAD

**Issue by lohikarhu** [hiroshootsfilm/shutterspeedtester#1]
using an LED lamp for the light source may cause a problem if the light had PWM active...using a phone 'torch'/'flashlight', or any led source, at less than full power will many times cause it to be 'blinking' hundreds of times per second, which will cause a false reading.

**Comment by hiroshootsfilm** [comment]
No plan to fix this.  We don't support PWM enabled lights. 
This is because we cannot distinguish between the PWM frequency and the shutter speed.  (ie. both can be 1/250 secs.)   Thanks!

**Comment by lohikarhu** [comment]
understood, mostly wanted to make some people aware of it, since i saw
questions about it.... trotzdem, Alles gute, freundlichen Grüßen Von GP
umgebung.
